---
# Example of usage:
# ansible-playbook -i inventory_file create_user.yml -e "server=server01 user_name=alex public_key_file=/path/to/dir/id_rsa.pub add_sudo=yes"

- hosts: "{{ server }}"
  become: true
  become_method: sudo

  vars:
    add_sudo: no

  tasks:
    - name: create user group with same name with user anem
      group: name={{ user_name }} state=present

    - name: create user
      user: name={{ user_name }} state=present 

    - name: add public key to authorized_key
      authorized_key: user={{ user_name }} key="{{ lookup('file', public_key_file) }}"

    - name: Add user to sudoers
      lineinfile:
        name: /etc/sudoers
        state: present
        regexp: '^{{ user_name }} ALL='
        line: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      when: add_sudo=="yes"
